export const SELECT_CLIENT = 'SELECT_CLIENT';
export const SELECT_PRODUCTS = 'SELECT_PRODUCTS';
export const PRODUCTS_QUANTITY = 'PRODUCTS_QUANTITY';
export const UPDATE_TOTAL = 'UPDATE_TOTAL';
export const SET_COVER_IMAGE = 'SET_COVER_IMAGE';